version: "3"
services:
  kaggle:
    build: env
    shm_size: '64gb'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    image: kaggle
    volumes:
      - .:/kaggle
    working_dir: /kaggle
    ports:
      - 8891:8888